"""add patient followup

Revision ID: 04b3a1a21b46
Revises: 8f4119778097
Create Date: 2026-08-26 22:55:14.489795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04b3a1a21b46'
down_revision = '8f4119778097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followup_no', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('visit_type', sa.String(length=30), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_followup_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_followups_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_followups_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_followups_followup_no'), ['followup_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_followups_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('bill_refunds', schema=None) as batch_op:
        batch_op.alter_column('refund_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('bill_no',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('refund_date')

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.alter_column('receipt_no',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint(batch_op.f('fk_deposit_patient'), type_='foreignkey')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('doc_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('doctors_doc_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_doctor_department'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_doctor_department'), 'departments', ['department_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_unique_constraint(batch_op.f('doctors_doc_code_key'), ['doc_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('doc_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_deposit_patient'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('receipt_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('bill_refunds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
        batch_op.alter_column('bill_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('patient_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('refund_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('patient_followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_followups_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_followup_no'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_department_id'))

    op.drop_table('patient_followups')
    # ### end Alembic commands ###
