"""add user role tables

Revision ID: 08a02e4fe462
Revises: 1163d5bc2509
Create Date: 2026-08-08 01:21:58.509072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a02e4fe462'
down_revision = '1163d5bc2509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('patient_no')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('allergies')
        batch_op.drop_column('title')
        batch_op.drop_column('visit_type')
        batch_op.drop_column('notes')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('religion')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('email')
        batch_op.drop_column('national_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('religion', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('visit_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
