"""Add ward table

Revision ID: 0b51f4333fe6
Revises: a26c06694d78
Create Date: 2026-08-28 14:04:15.302220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b51f4333fe6'
down_revision = 'a26c06694d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=50), nullable=False),
    sa.Column('ward_name', sa.String(length=150), nullable=False),
    sa.Column('ward_type', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_code'),
    sa.UniqueConstraint('ward_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wards')
    # ### end Alembic commands ###
