"""Add discharge reason and summary

Revision ID: 7600206a565c
Revises: 312356dda691
Create Date: 2026-08-29 23:38:17.814872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7600206a565c'
down_revision = '312356dda691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('department_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('ward_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('bed_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('admission_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('admissions_room_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admissions_ward_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admissions_department_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admissions_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('admissions_bed_id_fkey'), type_='foreignkey')
        batch_op.drop_column('discharge_summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discharge_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('admissions_bed_id_fkey'), 'beds', ['bed_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admissions_patient_id_fkey'), 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admissions_department_id_fkey'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admissions_ward_id_fkey'), 'wards', ['ward_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('admissions_room_id_fkey'), 'rooms', ['room_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('admission_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('bed_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('ward_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('department_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
