"""Create wards table

Revision ID: a26c06694d78
Revises: 04b3a1a21b46
Create Date: 2026-08-28 13:54:22.815104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a26c06694d78'
down_revision = '04b3a1a21b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_followups_department_id'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_followup_no'))
        batch_op.drop_index(batch_op.f('ix_patient_followups_patient_id'))

    op.drop_table('patient_followups')
    with op.batch_alter_table('bill_refunds', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('bill_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('patient_info_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_patient_corrections_created_at'))
        batch_op.drop_index(batch_op.f('idx_patient_corrections_patient_id'))
        batch_op.drop_index(batch_op.f('idx_patient_corrections_patient_no'))
        batch_op.create_index(batch_op.f('ix_patient_info_corrections_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_info_corrections_patient_no'), ['patient_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_info_corrections_patient_no'))
        batch_op.drop_index(batch_op.f('ix_patient_info_corrections_patient_id'))
        batch_op.create_index(batch_op.f('idx_patient_corrections_patient_no'), ['patient_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_patient_corrections_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_patient_corrections_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('bill_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('bill_refunds', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('patient_followups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('followup_no', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('visit_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prescription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_followup_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('patient_followups_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('patient_followups_department_id_fkey')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('patient_followups_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_followups_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_followups_pkey'))
    )
    with op.batch_alter_table('patient_followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_followups_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_followups_followup_no'), ['followup_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_followups_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_followups_department_id'), ['department_id'], unique=False)

    # ### end Alembic commands ###
