"""update room fields

Revision ID: ccedeb8797db
Revises: 0b51f4333fe6
Create Date: 2026-08-28 15:12:42.420724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccedeb8797db'
down_revision = '0b51f4333fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_name', sa.String(length=150), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
