"""Add bed setup

Revision ID: d9381e588ec0
Revises: ccedeb8797db
Create Date: 2026-08-28 16:36:42.333957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9381e588ec0'
down_revision = 'ccedeb8797db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_code', sa.String(length=50), nullable=False),
    sa.Column('bed_name', sa.String(length=100), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beds')
    # ### end Alembic commands ###
